kind: CronJob
apiVersion: batch/v1
metadata:
  name: vm-snapshot-win
  namespace: vmsample
spec:
  schedule: 42 12 * * *
  timeZone: Asia/Jakarta
  concurrencyPolicy: Allow
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: my-service-account
          containers:
            - resources: {}
              terminationMessagePath: /dev/termination-log
              name: vm-snapshot
              command:
                - /bin/bash
                - '-c'
              env:
                - name: TZ
                  value: Asia/Jakarta
              imagePullPolicy: IfNotPresent
              terminationMessagePolicy: File
              image: 'alfiilham26/oc:4.16'
              args:
                - |
                  #!/bin/bash

                  VM_NAME="win10-crimson-ant-48"
                  NAMESPACE="vmsample"
                  SNAPSHOT_NAME="snapshot-$(date +%Y-%m-%d-%H%M)"

                  # Log in to OpenShift (use service account token or in-cluster config)
                  oc login -u admin -p P@ssw0rd --server=https://api.ocp4.virtus-lab.net:6443 --insecure-skip-tls-verify

                  # Create a temporary YAML file for the VirtualMachineSnapshot
                  cat <<EOF > /tmp/vmsnapshot.yaml
                  apiVersion: snapshot.kubevirt.io/v1alpha1
                  kind: VirtualMachineSnapshot
                  metadata:
                    name: $SNAPSHOT_NAME
                    namespace: $NAMESPACE
                  spec:
                    source:
                      apiGroup: kubevirt.io
                      kind: VirtualMachine
                      name: $VM_NAME
                  EOF

                  # Apply the snapshot configuration
                  oc apply -f /tmp/vmsnapshot.yaml

                  # Optionally, remove the temporary YAML file
                  rm /tmp/vmsnapshot.yaml
          restartPolicy: OnFailure
